# Generated by Django 4.1.1 on 2022-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
