# Generated by Django 4.1.1 on 2022-11-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
