# Generated by Django 4.1.3 on 2022-11-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_department_name'),
        ('courses', '0005_delete_event'),
    ]

    operations = [
    ]
