# Generated by Django 4.1.1 on 2022-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_student_course_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studentslist',
            field=models.TextField(blank=True),
        ),
    ]
