# Generated by Django 4.1.1 on 2022-11-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_studentslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
